/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103C6_GPIO_driver.h"
#include "STM32F103C6_EXTI_driver.h"
#include "STM32F103C6_RCC_driver.h"
#include "STM32F103C6_USART_driver.h"
#include "STM32F103C6_SPI_driver.h"
#include "STM32F103C6_I2C_driver.h"
#include "I2C_Slave_EEPROM.h"


int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();


	//Test case 1
	uint8_t DATA1[] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	uint8_t DATA2[7]= {0};

	EEPROM_INIT();
	EEPROM_WRITE_DATA(0xAF, DATA1, 7);
	EEPROM_READ_DATA(0xAF, DATA2, 7);

	//Test case 2
	DATA1[0] = 0xA;
	DATA1[1] = 0xB;
	DATA1[2] = 0xC;
	DATA1[3] = 0xD;

	EEPROM_WRITE_DATA(0xFFF, DATA1, 4);
	EEPROM_READ_DATA(0xFFF, DATA2, 4);

	while(1){

	}
}
