/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

//RCC
#define RCC_BASE        0x40021000
#define RCC_APB2ENR    *(volatile uint32_t *) (RCC_BASE + 0x18)
#define RCC_IOPAEN      (1<<2)
#define RCC_IOPBEN      (1<<3)

//GPIOA
#define GPIOA_BASE      0x40010800
#define GPIOA_CRH      *(volatile uint32_t *) (GPIOA_BASE + 0x4)
#define GPIOA_CRL      *(volatile uint32_t *) (GPIOA_BASE + 0x00)
#define GPIOA_ODR      *(volatile uint32_t *) (GPIOA_BASE + 0x0c)
#define GPIOA_IDR      *(volatile uint32_t *) (GPIOA_BASE + 0x08)


//GPIOB
#define GPIOB_BASE      0x40010C00
#define GPIOB_CRH      *(volatile uint32_t *) (GPIOB_BASE + 0x4)
#define GPIOB_CRL      *(volatile uint32_t *) (GPIOB_BASE + 0x00)
#define GPIOB_ODR      *(volatile uint32_t *) (GPIOB_BASE + 0x0c)
#define GPIOB_IDR      *(volatile uint32_t *) (GPIOB_BASE + 0x08)

void clock_init(){
	//GPIOA clock
	RCC_APB2ENR |= (1<<2);

	//GPIOB clock
	RCC_APB2ENR |= (1<<3);
}

void GPIOA_init(){

	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOA_ODR = 0x0;

	//make PA1 input floating
	GPIOA_CRL |= (0b01<<6);
	//make PA13 input floating
	GPIOA_CRH |= (0b01<<22);
}

void GPIOB_init(){
	GPIOB_CRL = 0x0;
	GPIOB_CRH = 0x0;
	GPIOB_ODR = 0x0;

	//make PB1 push-pull output with 10MHz
	GPIOB_CRL |= (0b01<<4);
	//make PB13 push-pull output with 10MHz
	GPIOB_CRH |= (0b01<<20);
}

void my_wait (int x)
{
	unsigned int i , j ;
	for (i= 0 ; i<x ; i++)
		for (j= 0 ; j<255 ; j++);
}

int main(void)
{
	clock_init();
	GPIOA_init();
	GPIOB_init();

	while(1){

		//PA1 is connected as external PUR (default value is 1)
		if(((GPIOA_IDR & (1<<1))>>1) == 0){  //single press PA1

			//toggle PB1
			GPIOB_ODR ^= (1<<1);
			while(((GPIOA_IDR & (1<<1))>>1) == 0);//stay in loop while it is still pressed
		}

		//PA1 is connected as external PDR (default value is 0)
		if(((GPIOA_IDR & (1<<13))>>13) == 1){  // press PA13

			//toggle PB13;
			GPIOB_ODR ^= (1<<13);
			//it will stay in this if condition while the button is pressed (multi press)
		}

		my_wait(1);

	}


}
