/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define MCU_Act_As_Master
//#define MCU_Act_As_Slave

#include "STM32F103C6_GPIO_driver.h"
#include "STM32F103C6_EXTI_driver.h"
#include "STM32F103C6_RCC_driver.h"
#include "STM32F103C6_USART_driver.h"
#include "STM32F103C6_SPI_driver.h"


void clock_init(){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

uint16_t ch;

void IRQ_SPI(void){

#ifdef MCU_Act_As_Slave
	MCAL_SPI_TX_RX(SPI1, &ch, pollingdisable);
	MCAL_USART_Send_Data(USART1, &ch, enable);
#endif
}
void IRQ_USART(void){

#ifdef MCU_Act_As_Master
	MCAL_USART_Receive_Data(USART1, &ch, disable);
	MCAL_USART_Send_Data(USART1, &ch, enable);

	//send to spi
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, pollingenable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN4, 1);
#endif
}

int main(void)
{
	clock_init();

	USART_config usart_cfg;

	usart_cfg.Baud_rate = USART_BaudRate_115200;
	usart_cfg.HW_Flow_Control = USART_Flow_Control_NONE;
	usart_cfg.IRQ_Enable = USART_IRQ_ENABLE_RXNEIE;
	usart_cfg.P_IRQ_Callback = IRQ_USART;
	usart_cfg.Parity = USART_Parity_NONE;
	usart_cfg.Payload_length = USART_Payload_Length_8;
	usart_cfg.Stop_bits = USART_Stop_bit_1;
	usart_cfg.USART_MODE = USART_MODE_TX_RX;

	MCAL_USART_Init(USART1, &usart_cfg);
	MCAL_USART_GPIO_Set_Pins(USART1);


	SPI_config spi_config;
	//Common configuration
	spi_config.Clock_Phase = SPI_CLOCK_PHASE_SECOND_EDGE;
	spi_config.Clock_Polarity = SPI_CLOCK_POLARITY_HIGH_WHEN_IDLE;
	spi_config.Frame_Format = SPI_FRAME_MSB_FIRST;
	//assume pclk2 is 8 MHz
	spi_config.Data_size = SPI_DATA_SIZE_8_BIT;
	spi_config.SPI_Clock_Freq = SPI_BAUD_RATE_PRESCALER_8;
	spi_config.Comm_Mode = SPI_COMM_MODE_2LINES_TX_RX;

#ifdef MCU_Act_As_Master
	spi_config.Device_Mode = SPI_DEVICE_MODE_MASTER;
	spi_config.IRQ_Enable = SPI_IRQ_ENABLE_NONE;
	spi_config.NSS = SPI_NSS_SOFTWARE_INTERNAL_SS_SET;
	spi_config.P_IRQ_Callback = NULL;


	//we need to configure PA4 whih NSS is connected to it
	//it is not done in the MCAL_SPI_GPIO_Set_Pins function
	//because we configured NSS to be controlled by software and set it to 1
	//and in the MCAL_SPI_GPIO_Set_Pins function, it configures PA4 for hardware only

	GPIO_PinConfig_t pin_cfgg;
	pin_cfgg.GPIO_PinNumber =GPIO_PIN4;
	pin_cfgg.GPIO_MODE= GPIO_MODE_OUTPUT_PP;
	pin_cfgg.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA , &pin_cfgg);

	//force Slave select to be HIGH (idle)
	//it will be reset when we need to send (in the IRQ function)
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN4, 1);
#endif



#ifdef MCU_Act_As_Slave
	spi_config.Device_Mode = SPI_DEVICE_MODE_SLAVE;
	spi_config.IRQ_Enable = SPI_IRQ_ENABLE_RXNIE;
	spi_config.NSS = SPI_NSS_HARDWARE_SLAVE;
	spi_config.P_IRQ_Callback = IRQ_SPI;
#endif

	MCAL_SPI_Init(SPI1, &spi_config);
	MCAL_SPI_GPIO_Set_Pins(SPI1);

	while(1){

	}
}
